version: '3.8'

services:
  app:
    container_name: zlbg
    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      - ../..:/workspaces:cached

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
    # command: node dist/main.js

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    networks:
      - net
    depends_on:
      - db
      - redis
    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  web:
    image: nginx:latest
    volumes:
      - ./nginx:/etc/nginx/conf.d

    ports:
      - '80:80'
      - '3332:3332'
      - '3338:3338'
    depends_on:
      - app
    networks:
      - net
    
  redis:
    image: redis:latest
    networks:
      - net



  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    networks:
      - net
    # Add "forwardPorts": ["5432"] to **devcontainer.json** to forward PostgreSQL locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

volumes:
  postgres-data:

networks:
  net:
