version: '3.8'

services:
  app:
    container_name: zlbg
    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      - ../..:/workspaces:cached

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
    # command: node dist/main.js
    # command: yarn && yarn build && yarn start:prod
    expose:
      - "3333"
    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    networks:
      - net
    depends_on:
      - db
      - redis
    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  acme.sh:
    #教程 https://juejin.cn/post/7044777965262995470
    # docker exec acme.sh --register-account -m zenglbg@gmail.com --issue --dns dns_gd -d zlbg.cc -d *.zlbg.cc --force --dnssleep
    # https://github.com/acmesh-official/acme.sh/wiki/Run-acme.sh-in-docker
    image: neilpang/acme.sh
    container_name: acme.sh
    restart: always
    command: daemon
    environment:
      GD_Secret: Pxn1R4xP8PegGUNFKxbHXc
      GD_Key: eoBfvMne5tsZ_4cw6xWKwxxmKLwepBLDgJn
    volumes:
      - ../certs:/acme.sh
    networks:
      - net
 
  web:
    image: nginx:latest
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ../certs:/etc/nginx/certs
    ports:
      - '80:80'
      - '3332:3332'
      - '3338:3338'
    depends_on:
      - app
    networks:
      - net
  
  redis:
    image: redis:latest
    networks:
      - net


  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    networks:
      - net
    expose:
      - "5432"
    ports:
      - '5432:5432'
    # Add "forwardPorts": ["5432"] to **devcontainer.json** to forward PostgreSQL locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

volumes:
  postgres-data:

networks:
  net:
